# Generated by Django 2.1.3 on 2018-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentTaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.CharField(max_length=32)),
                ('forktruckID', models.CharField(max_length=32)),
                ('userName', models.CharField(max_length=32)),
                ('userPhone', models.CharField(max_length=32)),
                ('rent_startDate', models.DateTimeField()),
                ('rent_endDate', models.DateTimeField()),
                ('rent_usedDay', models.IntegerField()),
                ('rent_dayPrice', models.FloatField()),
                ('rent_transportPrice', models.FloatField()),
                ('rent_totalPrice', models.FloatField()),
                ('rent_securityPrice', models.FloatField()),
                ('rent_selfCost', models.FloatField()),
                ('attachment', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
